name: test-n-release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master branch
      uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  build-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master branch
      uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release
    - name: Upload release artifact
      uses: actions/upload-artifact@v2
      with:
        name: kbgen
        path: target/release/kbgen
  # release:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout master branch
  #     uses: actions/checkout@v2

  # release:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   - name: Build in Release Mode
  #     run: cargo build --release